config/routes.rb
Rails.application.routes.draw do
  
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  get 'signup' => 'users#new'
  get 'home'   => 'static_pages#home'
  get 'help'   => 'static_pages#help'
  get 'about'  => 'static_pages#about'
  get 'newRecipe' => 'recipes#new'
  get 'allRecipes' => 'recipes#index'
  
  get 'login' => 'sessions#new'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'
  
  root            'static_pages#home'
  
  resources :users
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :recipes

end

app/views/layouts/_footer.html.erb
  <footer class="navbar navbar-fixed-bottom navbar-inverse">
    <small>
      Recipe Saver - Copyright 2015
    </small>
    <br />


    <div nav class="navbar-nav navbar-right">
      <a href="#">
        <img title="Twitter" src="<%= asset_path( 'twitter.png' ) %>" alt="Twitter" width="25" height="25" />
      </a>
      <a href="#">
        <img title="Pinterest" src="<%= asset_path( 'pinterest.png' ) %>" alt="Pinterest" width="25" height="25" />
      </a> 
      <a href="#">
        <img title="Facebook" src="<%= asset_path( 'facebook.png' ) %>" alt="Facebook" width="25" height="25" />
      </a> 
      <a href="#">
        <img title="RSS" src="<%= asset_path( 'Rss.png' ) %>" alt="RSS" width="25" height="25" />
      </a>
    </div>
  </footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">

  <div class="container">
    <nav>
      
      <div class="navbar-brand">
        <%= link_to "Recipe Saver", root_path %>
      </div>
      
      <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form>
      
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "Help", help_path %></li>
        <li><%= link_to "About", about_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Users", users_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              Account <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <li><%= link_to "Profile", current_user %></li>
              <li><%= link_to "New Recipe", newRecipe_path %></li>
              <li><%= link_to "Settings", edit_user_path(current_user) %></li>
              <li class="divider"></li>
              <li>
                <%= link_to "Log out", logout_path, method: :delete %>
              </li>
            </ul>
          </li>
        <% else %>
          <li><%= link_to "Log In", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= yield(:title) %> | Recipe Saver</title>
    <%= stylesheet_link_tag 'application', media: 'all',
    'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
    <%= render 'shared/sidebar' %>
    <%= favicon_link_tag "whisk32.png" %>
</head>
<body>
  <%= render 'layouts/header' %>
  <div class="container">
    <% flash.each do |message_type, message| %>
      <div class="alert alert-<%= message_type %>"><%= message %></div>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <%= debug(params) if Rails.env.development? %>
  </div>
</body>
</html>